# Generated by Django 5.1.6 on 2025-07-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(max_length=50)),
                ('custom_details', models.TextField()),
                ('date', models.DateField()),
                ('fee', models.PositiveIntegerField()),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
