# Generated by Django 5.1.6 on 2025-07-19 19:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lashify_Artistry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('manual', 'Manual Transfer'), ('paystack', 'Paystack (Online)')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='custom_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(choices=[('nails', 'Nail Tech'), ('pedicure', 'Pedicure'), ('manicure', 'Manicure'), ('facial', 'Facial Treatment'), ('lashes', 'Lash Extension'), ('tattoo', 'Semi-Permanent Tattoo'), ('hair', 'Hair Styling')], max_length=20),
        ),
    ]
