# Generated by Django 5.1.6 on 2025-07-19 19:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lashify_Artistry', '0002_booking_created_at_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.AddField(
            model_name='booking',
            name='reated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
