# Generated by Django 5.1.6 on 2025-07-19 19:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lashify_Artistry', '0003_remove_booking_created_at_booking_reated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='reated_at',
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
