# Generated by Django 5.1.6 on 2025-07-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lashify_Artistry', '0004_remove_booking_reated_at_booking_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='verification_slip',
            field=models.ImageField(blank=True, null=True, upload_to='verification_slips/'),
        ),
    ]
