# Generated by Django 5.2.4 on 2025-07-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lashify_Artistry', '0006_booking_confirmation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(choices=[('Gel nails', 'Gel nails'), ('Acrylic nails', 'Acrylic nails'), ('manicure', 'Manicure'), ('facial', 'Facial Treatment'), ('lashes', 'Lash Extension'), ('tattoo', 'Semi-Permanent Tattoo'), ('hair', 'Hair Styling'), ('Pedicure', 'Pedicure')], max_length=20),
        ),
    ]
