# Generated by Django 5.2.4 on 2025-08-13 16:39

import Lashify_Artistry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lashify_Artistry', '0007_alter_booking_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reference',
            field=models.CharField(default=Lashify_Artistry.models.generate_reference_code, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(choices=[('tattoo', 'Semi Permanent Tattoos'), ('GNSL_nails', 'Gel nails (short length)'), ('GNML_nails', 'Gel nails (medium length)'), ('GNLL_nails', 'Gel nails (long length)'), ('ANSLP_nails', 'Acrylic nails short length plain'), ('ANSLFT_nails', 'Acrylic nails short length french tips'), ('ANSLED_nails', 'Acrylic nails short length extra designs'), ('ANMLP_nails', 'Acrylic nails medium length plain'), ('ANMLFT_nails', 'Acrylic nails medium length french tips'), ('ANMLED_nails', 'Acrylic nails medium length extra designs'), ('ANLLP_nails', 'Acrylic nails long length plain'), ('ANLLFT_nails', 'Acrylic nails long length french tips'), ('ANLLED_nails', 'Acrylic nails long length extra designs'), ('ANELLP_nails', 'Acrylic nails extra long length plain'), ('ANELLFT_nails', 'Acrylic nails extra long length french tips'), ('ANELLED_nails', 'Acrylic nails extra long length extra designs'), ('C_lashes', 'Classic Lashes'), ('H_lashes', 'Hybrid Lashes'), ('V_lashes', 'Volume Lashes'), ('MV_lashes', 'Mega Volume Lashes'), ('N_pedicure', 'Normal Pedicure'), ('F_pedicure', 'French Pedicure'), ('P_pedicure', 'Paraffin Pedicure'), ('hair', 'Hair Styling'), ('manicure', 'Manicure'), ('facial', 'Facial Treatment')], max_length=20),
        ),
    ]
